### ISSUE TITLE
[GLPI 10] - Cannot declare GLPI\Socket

### ISSUE THREAD

**Issue by stdglpi** [glpi-project/glpi#10228]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

Hello,

i'm facing to this issue directly after the login and password step and then impossibe to fix it.

I tried to follow the steps on theses two fixed tickets | #10168 #10130 but still hapenning.

![image](https://user-images.githubusercontent.com/63521311/147381779-0dda8e83-5807-4adf-8d45-edc061a22085.png)
![image](https://user-images.githubusercontent.com/63521311/147381785-7905f900-c008-47f7-a22b-1ee1c35cdb36.png)

### Relevant log output

```shell
In the php-errors.log

[2021-12-25 09:47:10] glpiphplog.ALERT:   *** PHP Compile Error (64): Cannot declare class Glpi\Socket, because the name is already in use in C:\inetpub\wwwroot\glpi\src\Socket.php at line 0  
[2021-12-25 09:56:03] glpiphplog.ALERT:   *** PHP Compile Error (64): Cannot declare class Glpi\Socket, because the name is already in use in C:\inetpub\wwwroot\glpi\src\Socket.php at line 0  
[2021-12-25 09:56:04] glpiphplog.ALERT:   *** PHP Compile Error (64): Cannot declare class Glpi\Socket, because the name is already in use in C:\inetpub\wwwroot\glpi\src\Socket.php at line 0  
[2021-12-25 09:56:17] glpiphplog.ALERT:   *** PHP Compile Error (64): Cannot declare class Glpi\Socket, because the name is already in use in C:\inetpub\wwwroot\glpi\src\Socket.php at line 0
```

### Page URL

https://glpi/front/ticket.php

### Your GLPI setup information

Windows server 2016 [IIS]
PHP 7.4 tls
Mysql Server 8.0

plugins : 
Form creator
News
Tags

**Comment by cconard96** [comment]
This issue was fixed by:
https://github.com/glpi-project/glpi/pull/10169

Other class-loading issues were fixed in these PRs:
https://github.com/glpi-project/glpi/pull/10187
https://github.com/glpi-project/glpi/pull/10101
https://github.com/glpi-project/glpi/pull/10100

**Comment by stdglpi** [comment]
thank you @cconard96 

I found the first problem and I share it here : 
- I upgraded MYSQL 5.X to 8 (Then I had the error with the socket class)

I tried to used this solution : Fix Socket namespace handling #10169

After that, the problem persisted, I tried to upgrade my Php version 7.4 to 8.0 then all is working now.

thank you
