### ISSUE TITLE
0.90.1 - SSO - expired session - security die. trying to load an forbidden class name

### ISSUE THREAD

**Issue by mathieuchateau** [glpi-project/glpi#1280]
Environnent:
-glpi version 0.90.1
-red hat 7.3
-kerberos authentication

Issue:
When connecting directly to a final url and not home page, Apache does authenticate user but GLPI generate error message:
security die. trying to load an forbidden class name

Analyze:
GLPI should create a new session when current session is expired or no session exist. For example send back to home page and then back to original url transparently.

how to reproduce:
Way 1:
1/go to a glpi computer for example
2/ copy and paster full url to another browser or in private session from same browser
3/ error message: security die. trying to load an forbidden class name

Way 2:
1/ Go to glpi using SSO
2/open let's say a computer detail page
3/ wait for session to expire
4/click on any link within glpi
5/ error message: security die. trying to load an forbidden class name

**Comment by orthagh** [comment]
Hello @mathieuchateau 

Your "way 1" to reproduce this issue is invalid.
Actually i can go to a computer detail without session (in private session of my browser).

To be sure, i'll encourage you to update your glpi to the last bugfixes version of 0.90: 
[0.90 release](https://github.com/glpi-project/glpi/releases/download/0.90.5/glpi-0.90.5.tar.gz)

I think your issue may be already fixed in his last release.

**Comment by mathieuchateau** [comment]
Hello,

I still reproduce with version 9.1.2.
How I reproduce:
-Open browser
-go to glpi welcome page
-go to computer list page
-wait let's say 1 hour
-Click on 1 computer name to open detail page
