### ISSUE TITLE
Field locking problem

### ISSUE THREAD

**Issue by TestOrganigrammeBA** [glpi-project/glpi#13296]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

When updating computers via FusionInventory, some fields are modified with strange information.

I inquired and noticed that it was possible to lock fields, however, when I manually modify the fields, and go to the "Locks" tab, nothing appears.

Here is the SQL log file: 
[sql-error.log](https://github.com/glpi-project/glpi/files/10011264/sql-error.log)

### Steps To reproduce

1. Editing the Model field of a computer
2. Search for the previously locked field in the "Locks" tab of the computer
3. No field is locked, because when updating the form via FusionInventory, the field is modified.

![image](https://user-images.githubusercontent.com/91662361/201883663-f2255d1f-208c-4648-83e1-3bd8f3b2722a.png)

### Your GLPI setup information

Operating system: Linux srvglpi 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64
PHP 8.0.25 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, shmop, snmp, sockets, sodium, sqlite3, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at srvweb Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Server Software: Debian 10
	Server Version: 10.3.36-MariaDB-0+deb10u2
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpiuser@localhost/glpidb
	Host info: Localhost via UNIX socket
	
PHP version (8.0.25) is supported.PHP version (8.0.25) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.36) is supported.Database engine version (10.3.36) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
The following directories should be placed outside "/var/www/html/glpi": ‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR") ‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR") You can ignore this suggestion if you are certain that these directories are not accessible through your web server.The following directories should be placed outside "/var/www/html/glpi":
‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR")
‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
Sessions configuration is secured.Sessions configuration is secured.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by stonebuzz** [comment]
Can you confirm that ```is_global``` column from ```glpi_lockedfields``` table is missing from your database ?

Best regards

**Comment by TestOrganigrammeBA** [comment]
Hello,
Thank you for your quick reply.

Yes I confirm that the is_global column is missing from the glpi_lockedfileds table

![image](https://user-images.githubusercontent.com/91662361/201886889-b427e80f-7276-4286-b347-86e8e7f63ebf.png)

**Comment by stonebuzz** [comment]
I don't know why but migration from GLPI 10.0.0 to GLPI 10.0.1 did not add this column !

Can you run this command (at GLPI root folder)

```shell 
php bin/console glpi:database:check_schema_integrity 
```

Best regards

**Comment by TestOrganigrammeBA** [comment]
Here is the output of the command:

![image](https://user-images.githubusercontent.com/91662361/201893225-ff566292-923d-4946-bf0c-05c75a15f403.png)

**Comment by stonebuzz** [comment]
Can you run this command (at GLPI root folder)

```shell
php bin/console glpi:database:update --force
```
Schema integrity should be fixed.

Best regards

**Comment by TestOrganigrammeBA** [comment]
Hello,

Here is the output of the command:
![image](https://user-images.githubusercontent.com/91662361/201921328-e96ad052-a2fd-4491-ae7c-024491331c7d.png)


Cordially.

**Comment by stonebuzz** [comment]
Please drop view (is not part of GLPI)

**Comment by stonebuzz** [comment]
```is_global``` column is OK ?

**Comment by TestOrganigrammeBA** [comment]
The table still does not contain the is_global column : 
![image](https://user-images.githubusercontent.com/91662361/201924693-44590771-6a3c-4ee8-8c94-ce700ad63f6f.png)

**Comment by cedric-anne** [comment]
Replaying latest migration will not fix this, as this field has been created multiple versions ago. The only way to fix this is to recreate the field manually in database.

**Comment by TestOrganigrammeBA** [comment]
No worries, what is the type of the column?

**Comment by trasher** [comment]
You can find it in the empty.sql file under instal directory
