### ISSUE TITLE
v11.0.2 Financial and Administrative Information fields not displaying values for Custom Assets in Assets->Global view

### ISSUE THREAD

**Issue by andrewc-ui** [glpi-project/glpi#22290]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11.0.2 - On-Prem

### Bug description

Creating a Custom Asset definition. (Setup->Asset Definitions), then adding "Financial and administrative information" field data to the Assets-> Global view for the custom asset, does not show "Financial and administrative information" field values for custom assets. Fieldname headers are displayed ok, simply no data shown. Core assets display this data ok.
Profiles, capacities etc are all confirmed set for the custom assets

### Relevant log output

```shell
There are no relevant log entries to report for this issue, there is no error, just no data selection/display for the custom asset(s).
```

### Page URL

[instance]/front/allassets.php

### Steps To reproduce

Confirming "Enable the financial and administrative information by default" is set to yes in setup.
1. Create a Custom Asset definition. (Setup->Asset Definitions)
2. Ensure profiles set accordingly
3. Ensure capacities include "Financial and administrative information"
4. Create a new instance of your custom asset.
5. Enter some "Financial and administrative information" field data (e,g Business Criticity) and save
6. Now choose Assets->Global
7. Custom asset displayed in the list, ok so far
8. Select "Select default items to show" add the 'Business Criticity" field to the global view.
9. Note the column heading is displayed "Financial and administrative information - Business Criticity", however the value of the field for your custom asset is not displayed. All fields in the 'Financial and administrative information" section of custom assets can be added to the Assets->Global view and have the headings displayed, but no values are shown in the view for these fields.
10. Note other asset types (core) display the values for the "Financial and administrative information" fields with no issue.

Also confirmed issue present in a second v11.0.2 instance as corroboration.

### Your GLPI setup information

[detailssummaryGLPI informationsummaTEST-11.0.2.txt](https://github.com/user-attachments/files/24045867/detailssummaryGLPI.informationsummaTEST-11.0.2.txt)

### Anything else?

The display of Financial and Admin info across all assets, core and custom alike is key to our goals in using GLPI. Hope you can advise on way forward here.

**Comment by trasher** [comment]
This has been fixed in latest release.

**Comment by andrewc-ui** [comment]
I originally identified this issue in an upgraded instance 11.0.2->11.0.4 and elected to revert back to 11.0.2 where I reported this issue here. The issue was present in 11.0.4.

**Comment by andrewc-ui** [comment]
I have just repeated an upgrade from 11.0.2->11.0.4. On the php bin/console db:update command, noticed this anomaly:

<img width="422" height="346" alt="Image" src="https://github.com/user-attachments/assets/b516fb4a-8857-49ef-ac18-8d5fea07924c" />

**Comment by andrewc-ui** [comment]
I have repeated the reported issue (at v11.0.2) on the upgraded 11.0.4 and the issue persists

**Comment by andrewc-ui** [comment]
Hi Johan.
Could you please read updates I have posted against this issue?

Could you please re-open accordingly?

Regards

Andrew Curtis

**Comment by cedric-anne** [comment]
I confirm the issue.

**Comment by andrewc-ui** [comment]
Please advise of applicable workarounds etc for this issue for current release?

**Comment by trasher** [comment]
> Please advise of applicable workarounds etc for this issue for current release?

Wait for a fix to be proposed.
