### ISSUE TITLE
Home is loading slow.

### ISSUE THREAD

**Issue by estevamota** [glpi-project/glpi#6765]
**Describe the bug**

Login user is glpi on GLPI System after Home screen is loading almost more than 25 seconds.

**Page(s) URL**

front/central.php

**To reproduce**

1. Open in GLPI system
2. Login is glpi
3. Button is post
4. Home Central is slow

**Expected behavior**

High CPU usage with Mysql (MariaDB 10)

**Logs**

Errors do not appear when logged in is glpi on GLPI system. I made tail -f * -error.log

**Screenshots**

![Screenshot from 2020-01-03 10-30-17](https://user-images.githubusercontent.com/23287031/71726183-16cdd300-2e15-11ea-96d4-786ac54086ed.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.4.4 (/tic => /var/www/glpi/tic)
Installation mode: TARBALL

Server
 
Operating system: Linux srvhmc04.local 3.10.0-1062.7.1.el7.x86_64 #1 SMP Mon Dec 2 17:33:29 UTC 2019 x86_64
PHP 7.2.26 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bz2, calendar, cgi-fcgi, ctype, curl, date, dom,
	exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcntl, pcre,
	pdo_mysql, pdo_sqlite, readline, session, sockets, sqlite3, standard, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl,
	zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) PHP/5.4.45 ()
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.4.10-MariaDB
	Server SQL Mode: 
	Parameters: glpi_tic@127.0.0.1/glpi_tic
	Host info: 127.0.0.1 via TCP/IP
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
Zend OPcache extension is installed
xmlrpc extension is installed
exif extension is installed
imap extension is not present
APCu extension is not present
CAS extension is not present
Database version seems correct (10.4.10) - Perfect!Database version seems correct (10.4.10) - Perfect!
OK/var/www/glpi/tic/files/_log : OK
OK/var/www/glpi/tic/config : OK
OK/var/www/glpi/tic/files : OK
OK/var/www/glpi/tic/files/_dumps : OK
OK/var/www/glpi/tic/files/_sessions : OK
OK/var/www/glpi/tic/files/_cron : OK
OK/var/www/glpi/tic/files/_graphs : OK
OK/var/www/glpi/tic/files/_lock : OK
OK/var/www/glpi/tic/files/_plugins : OK
OK/var/www/glpi/tic/files/_tmp : OK
OK/var/www/glpi/tic/files/_cache : OK
OK/var/www/glpi/tic/files/_rss : OK
OK/var/www/glpi/tic/files/_uploads : OK
OK/var/www/glpi/tic/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK
OKSELinux mode is Disabled

Libraries
 
htmLawed version 1.2.4 in (/var/www/glpi/tic/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/var/www/glpi/tic/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/var/www/glpi/tic/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/var/www/glpi/tic/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/tic/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/tic/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/tic/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/glpi/tic/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/var/www/glpi/tic/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/var/www/glpi/tic/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/var/www/glpi/tic/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/var/www/glpi/tic/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/tic/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/glpi/tic/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/tic/vendor/symfony/console)
leafo/scssphp in (/var/www/glpi/tic/vendor/leafo/scssphp/src)

LDAP directories
 
Server: 'private.local', Port: '389', BaseDN: 'DC=PRIVATE, DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'servico_linux@private.local', Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (anonymous@172.27.37.148)

Mails receivers
 

Plugins list
 
```

**Additional context**

_**High CPU with Mysql**_

![Screenshot from 2020-01-03 10-32-13](https://user-images.githubusercontent.com/23287031/71726228-32d17480-2e15-11ea-8e56-1868573e77da.png)

**_Debug_**

![Screenshot from 2020-01-03 10-32-25](https://user-images.githubusercontent.com/23287031/71726250-4250bd80-2e15-11ea-8897-31a0020604be.png)

**_Query with Mysql_**

```
MariaDB [glpi_tic]> SELECT DISTINCT `glpi_tickets`.`id`
    -> FROM `glpi_tickets`
    -> LEFT JOIN `glpi_tickets_users` ON (`glpi_tickets`.`id` = `glpi_tickets_users`.`tickets_id`)
    -> LEFT JOIN `glpi_groups_tickets` ON (`glpi_tickets`.`id` = `glpi_groups_tickets`.`tickets_id`)
    -> INNER JOIN `glpi_ticketsatisfactions` ON (`glpi_tickets`.`id` = `glpi_ticketsatisfactions`.`tickets_id`)
    -> INNER JOIN `glpi_entities` ON (`glpi_entities`.`id` = `glpi_tickets`.`entities_id`)
    -> WHERE `glpi_tickets`.`is_deleted` = 0 AND ( (`glpi_tickets_users`.`users_id` = '2' AND `glpi_tickets_users`.`type` = '1') OR `glpi_tickets`.`users_id_recipient` = '2') AND `glpi_tickets`.`status` = '6' AND (`glpi_entities`.`inquest_duration` = 0 OR DATEDIFF(ADDDATE(`glpi_ticketsatisfactions`.`date_begin`, INTERVAL `glpi_entities`.`inquest_duration` DAY), CURDATE()) > 0) AND `glpi_ticketsatisfactions`.`date_answered` IS NULL
    -> ORDER BY `glpi_tickets`.`date_mod` DESC;
Empty set (12.355 sec)
```

_**Analyze with Mysql (MariaDB)**_

```
MariaDB [glpi_tic]> explain SELECT DISTINCT `glpi_tickets`.`id`
    -> FROM `glpi_tickets`
    -> LEFT JOIN `glpi_tickets_users` ON (`glpi_tickets`.`id` = `glpi_tickets_users`.`tickets_id`)
    -> LEFT JOIN `glpi_groups_tickets` ON (`glpi_tickets`.`id` = `glpi_groups_tickets`.`tickets_id`)
    -> INNER JOIN `glpi_ticketsatisfactions` ON (`glpi_tickets`.`id` = `glpi_ticketsatisfactions`.`tickets_id`)
    -> INNER JOIN `glpi_entities` ON (`glpi_entities`.`id` = `glpi_tickets`.`entities_id`)
    -> WHERE `glpi_tickets`.`is_deleted` = 0 AND ( (`glpi_tickets_users`.`users_id` = '2' AND `glpi_tickets_users`.`type` = '1') OR `glpi_tickets`.`users_id_recipient` = '2') AND `glpi_tickets`.`status` = '6' AND (`glpi_entities`.`inquest_duration` = 0 OR DATEDIFF(ADDDATE(`glpi_ticketsatisfactions`.`date_begin`, INTERVAL `glpi_entities`.`inquest_duration` DAY), CURDATE()) > 0) AND `glpi_ticketsatisfactions`.`date_answered` IS NULL
    -> ORDER BY `glpi_tickets`.`date_mod` DESC;
+------+-------------+--------------------------+------------+----------------------------------------------------------+-------------+---------+----------------------------------------------+-------------+---------------------------------------------------------------------+
| id   | select_type | table                    | type       | possible_keys                                            | key         | key_len | ref                                          | rows        | Extra                                                               |
+------+-------------+--------------------------+------------+----------------------------------------------------------+-------------+---------+----------------------------------------------+-------------+---------------------------------------------------------------------+
|    1 | SIMPLE      | glpi_ticketsatisfactions | ALL        | tickets_id                                               | NULL        | NULL    | NULL                                         | 7963        | Using where; Using temporary; Using filesort                        |
|    1 | SIMPLE      | glpi_tickets             | ALL|filter | PRIMARY,status,entities_id,users_id_recipient,is_deleted | |is_deleted | |1      | NULL                                         | 16355 (50%) | Using where; Using join buffer (flat, BNL join); Using rowid filter |
|    1 | SIMPLE      | glpi_tickets_users       | ref        | unicity                                                  | unicity     | 4       | glpi_tic.glpi_ticketsatisfactions.tickets_id | 1           | Using where; Using index                                            |
|    1 | SIMPLE      | glpi_groups_tickets      | ref        | unicity                                                  | unicity     | 4       | glpi_tic.glpi_ticketsatisfactions.tickets_id | 1           | Using index                                                         |
|    1 | SIMPLE      | glpi_entities            | ALL        | PRIMARY                                                  | NULL        | NULL    | NULL                                         | 3           | Using where; Using join buffer (flat, BNL join)                     |
+------+-------------+--------------------------+------------+----------------------------------------------------------+-------------+---------+----------------------------------------------+-------------+---------------------------------------------------------------------+
5 rows in set (0.002 sec)
```

How do I solve what performance or optimization in the database is MariaDB ?

**Comment by olivierDM40** [comment]
Hi, exactly the same problem for me. 
Problem still present in 9.5.2 
Thank you for your help optimizing the query, or giving us some indexes to add in database

**Comment by orthagh** [comment]
Hello, to check if you have missing keys in your database tables, could attach (don't copy paste directly)  the result of the following command:

`bin/console glpi:database:check`

**Comment by olivierDM40** [comment]
Hi, here is the result of database check
Thank you 
[checkglpidatabase.zip](https://github.com/glpi-project/glpi/files/5447258/checkglpidatabase.zip)

**Comment by cedric-anne** [comment]
Hi,

We do not reproduce this issue on a database that as much elements than yours. This issue may be related to your database server configuration.

However, this [commit](https://github.com/glpi-project/glpi/commit/c006e7fff3be07796ad9cd26c11864f0e12c7c34) could help you. Indeed, I saw that slow queries were done twice and I fixed it.

Regards

**Comment by M-Falken** [comment]
Hi
Same issue for me.
Suddenly happen with my GLPI version 9.4.5 on suddenly Thursday November 5.
Urgent migration to version 9.5.2 hoping for a resolution of the problem, but no.
The login time is awfully long (at least 25s) or the Mysql server gives up and kills the process.
Note that the first tab of each section (ticket, printer, user, etc.) remains blocked on the loading gif while if you click on one of the other tabs, the content is displayed.
However no modification made beforehand.
My other sites are functioning quite normally.
PHP 7.4.11 - MariaDB 10.2.35

**Comment by olivierDM40** [comment]
Hi after testing the 3 patched files, the issue is still here, no visible impact on response time.
Thank you

**Comment by M-Falken** [comment]
> 
> 
> Hi after testing the 3 patched files, the issue is still here, no visible impact on response time.
> Thank you

Are you with Maria DB 10.2.35 ?

**Comment by olivierDM40** [comment]
Hi, for my side, i am in MariaDB 10.4.5 and it's not possible for me to downgrade Maria to 10.2.34
Thank you

**Comment by M-Falken** [comment]
So I can't really tell for the 10.4.5 but MariaDB 10.4.5 is a Release Candidate (RC) release.
You should not use this version at all but the 10.4.17 (the 10.4.16 as also a big bug)
https://mariadb.com/kb/en/mariadb-10417-release-notes/

The bug occur with v10.2.35 and v10.3.26, in those cases you should go back with previous versions respectively 10.2.34 and 10.3.25

**Comment by olivierDM40** [comment]
Hi, i've upgraded my MariaDB release to 10.4.17 and it solves the problem. 
Thank you

**Comment by cedric-anne** [comment]
Hi,

As problem seems to be due to a performance issue in MariaDB, which can be solved by an update of it, I close this issue.

Regards
