### ISSUE TITLE
Mailgate running perpetually

### ISSUE THREAD

**Issue by phhyvernat** [glpi-project/glpi#8002]
Hi all, we have since few days the mailgate automatic actions continuously running even i stop it. i receive a mail that this action is in error.
1 collector is parametered, when i click on 
Everything goes well for 4 months and a day, problem with mailgate. Here's the versions and log error :

glpi 5.1
php74
mysql8.0.21
Apache24-2.4.13

[PHP Modules]
bz2
Core
ctype
curl
date
exif
fileinfo
filter
gd
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
Reflection
session
SimpleXML
sodium
SPL
standard
xml
xmlrpc
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

CRONTAB : 

* * * * * /usr/local/bin/php  /usr/local/www/glpi/front/cron.php &>/dev/null
* * * * * /usr/local/bin/php  /usr/local/www/glpi/front/cron.php mailgate
* * * * * /usr/local/bin/php  /usr/local/www/glpi/front/cron.php queuednotification

LOG : 

[2020-09-25 11:31:09] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Storage\Exception\InvalidArgumentException: Header with Name message_id or message_id not found in /usr/local/www/glpi/vendor/laminas/laminas-mail/src/Storage/Part.php at line 307
  Backtrace :
  inc/mailcollector.class.php:1429                   Laminas\Mail\Storage\Part->getHeader()
  inc/mailcollector.class.php:934                    MailCollector->getHeaders()
  inc/mailcollector.class.php:735                    MailCollector->buildTicket()
  front/mailcollector.form.php:77                    MailCollector->collect()

Thanks a lot for the answer. We are an hospital and

**Comment by cedric-anne** [comment]
Hi,

Multiple mail collector issues has been fixed recently. Please try with [latest nightly build](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22) to see if problem persist.

Regards

**Comment by phhyvernat** [comment]
Hi,

 

Thanks for your answer. 

 

I searched for a fix and replace the mailcollector.class.php you posted the 30 july but always the same error…

 

regards

Description : P Hyvernat 2017

 

De : Cédric Anne [mailto:notifications@github.com] 
Envoyé : vendredi 25 septembre 2020 13:14
À : glpi-project/glpi
Cc : phhyvernat; Author
Objet : Re: [glpi-project/glpi] Mailgate running perpetually (#8002)

 

Hi,

Multiple mail collector issues has been fixed recently. Please try with latest nightly build <https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22>  to see if problem persist.

Regards

**Comment by cedric-anne** [comment]
It is possible that some fixes have been made more recently.

Please try to install the latest nightly build on a test server to see i problem persist, and, in this case, attach here the mail that cause the problem  (in .eml format) and we will be able to debug your issue.

**Comment by phhyvernat** [comment]
Ok sorry, i try to download the latest nightly build and install it on the server

**Comment by phhyvernat** [comment]
Thanks ,

 

To install files i just copy the directory glpi and replace files ? 

 

 

 

Description : P Hyvernat 2017

 

De : Cédric Anne [mailto:notifications@github.com] 
Envoyé : vendredi 25 septembre 2020 13:27
À : glpi-project/glpi
Cc : phhyvernat; Author
Objet : Re: [glpi-project/glpi] Mailgate running perpetually (#8002)

 

It is possible that some fixes have been made more recently.

Please try to install the latest nightly build on a test server to see i problem persist, and, in this case, attach here the mail that cause the problem (in .eml format) and we will be able to debug your issue.

**Comment by phhyvernat** [comment]
Hi,

everything is ok i installed nightly build 9.5.2 and mailgate return ok 

Thanks a lot for your help

appreciate
