### ISSUE TITLE
The dropdown list "group""Assigned to" drop-down list is empty

### ISSUE THREAD

**Issue by Riesuu** [glpi-project/glpi#8806]
GLPI 9.5.4

The "Assigned to" drop-down list is empty, on the other hand, no problem with observers.

![2021-03-10 09_26_18-Clipboard](https://user-images.githubusercontent.com/17006344/110599039-c4a7e080-8182-11eb-8cf5-79010f1f3d4a.png)

**Comment by cedric-anne** [comment]
Hi,

Do you have something in your GLPI logs or in browser console ?

Do you have some active plugins ? In this case, could you deactivate them and test again ?

Regards

**Comment by xacobofg** [comment]
I encountered a similar error with the location dropdown.
In order to load the values in the dropdown I had to comment line 2188 of the inc/dropdown.class.php file
`  

      // check if asked itemtype is the one originaly requested by the form
      if (!Session::validateIDOR($post)) {
         return;
      }`

**Comment by cedric-anne** [comment]
> I encountered a similar error with the location dropdown.
> In order to load the values in the dropdown I had to comment line 2188 of the inc/dropdown.class.php file
> `
> 
> ```
>   // check if asked itemtype is the one originaly requested by the form
>   if (!Session::validateIDOR($post)) {
>      return;
>   }`
> ```

@xacobofg 

This is a security check ! Do not comment this , it has been done to prevent exposal of sensitive data.

Regards

**Comment by Riesuu** [comment]
php-errors:

`[2021-03-10 06:26:04] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "glpiactive_entity" in /var/www/html/glpi/marketplace/formcreator/inc/issue.class.php at line 400
  Backtrace :
  inc/commondbtm.class.php:3644                      PluginFormcreatorIssue->rawSearchOptions()
  inc/commondbtm.class.php:3951                      CommonDBTM->searchOptions()
  inc/commondbtm.class.php:4023                      CommonDBTM->getSearchOptionByField()
  inc/commondbtm.class.php:1121                      CommonDBTM->filterValues()
  marketplace/formcreator/hook.php:350               CommonDBTM->add()
  inc/plugin.class.php:1350                          plugin_formcreator_hook_add_ticket()
  inc/commondbtm.class.php:1185                      Plugin::doHook()
  inc/mailcollector.class.php:824                    CommonDBTM->add()
  inc/mailcollector.class.php:1746                   MailCollector->collect()
  inc/crontask.class.php:845                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  
[2021-03-10 07:55:02] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "glpiactive_entity" in /var/www/html/glpi/marketplace/formcreator/inc/issue.class.php at line 400
  Backtrace :
  inc/commondbtm.class.php:3644                      PluginFormcreatorIssue->rawSearchOptions()
  inc/commondbtm.class.php:3951                      CommonDBTM->searchOptions()
  inc/commondbtm.class.php:4023                      CommonDBTM->getSearchOptionByField()
  inc/commondbtm.class.php:1121                      CommonDBTM->filterValues()
  marketplace/formcreator/hook.php:350               CommonDBTM->add()
  inc/plugin.class.php:1350                          plugin_formcreator_hook_add_ticket()
  inc/commondbtm.class.php:1185                      Plugin::doHook()
  inc/mailcollector.class.php:824                    CommonDBTM->add()
  inc/mailcollector.class.php:1746                   MailCollector->collect()
  inc/crontask.class.php:845                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  
[2021-03-10 08:16:02] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "glpiactive_entity" in /var/www/html/glpi/marketplace/formcreator/inc/issue.class.php at line 400
  Backtrace :
  inc/commondbtm.class.php:3644                      PluginFormcreatorIssue->rawSearchOptions()
  inc/commondbtm.class.php:3951                      CommonDBTM->searchOptions()
  inc/commondbtm.class.php:4023                      CommonDBTM->getSearchOptionByField()
  inc/commondbtm.class.php:1121                      CommonDBTM->filterValues()
  marketplace/formcreator/hook.php:350               CommonDBTM->add()
  inc/plugin.class.php:1350                          plugin_formcreator_hook_add_ticket()
  inc/commondbtm.class.php:1185                      Plugin::doHook()
  inc/mailcollector.class.php:824                    CommonDBTM->add()
  inc/mailcollector.class.php:1746                   MailCollector->collect()
  inc/crontask.class.php:845                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  
[2021-03-10 08:21:02] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "glpiactive_entity" in /var/www/html/glpi/marketplace/formcreator/inc/issue.class.php at line 400
  Backtrace :
  inc/commondbtm.class.php:3644                      PluginFormcreatorIssue->rawSearchOptions()
  inc/commondbtm.class.php:3951                      CommonDBTM->searchOptions()
  inc/commondbtm.class.php:4023                      CommonDBTM->getSearchOptionByField()
  inc/commondbtm.class.php:1121                      CommonDBTM->filterValues()
  marketplace/formcreator/hook.php:350               CommonDBTM->add()
  inc/plugin.class.php:1350                          plugin_formcreator_hook_add_ticket()
  inc/commondbtm.class.php:1185                      Plugin::doHook()
  inc/mailcollector.class.php:824                    CommonDBTM->add()
  inc/mailcollector.class.php:1746                   MailCollector->collect()
  inc/crontask.class.php:845                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  
[2021-03-10 08:23:01] glpiphplog.ERROR: CommonITILObject::getTemplateFieldName() in /var/www/html/glpi/inc/commonitilobject.class.php line 7950
Missing type for Ticket template!  {"user":"2256@sai-glpi-prd-01"} 
[2021-03-10 08:24:22] glpiphplog.ERROR: CommonITILObject::getTemplateFieldName() in /var/www/html/glpi/inc/commonitilobject.class.php line 7950
Missing type for Ticket template!  {"user":"2256@sai-glpi-prd-01"} 
[2021-03-10 08:28:30] glpiphplog.ERROR: CommonITILObject::getTemplateFieldName() in /var/www/html/glpi/inc/commonitilobject.class.php line 7950
Missing type for Ticket template!  {"user":"2203@sai-glpi-prd-01"} 
[2021-03-10 08:28:59] glpiphplog.ERROR: CommonITILObject::getTemplateFieldName() in /var/www/html/glpi/inc/commonitilobject.class.php line 7950
Missing type for Ticket template!  {"user":"2203@sai-glpi-prd-01"} 
[2021-03-10 08:29:31] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/inc/html.class.php line 7495
css/palettes/icecream.scss is new, loading  {"user":"2051@sai-glpi-prd-01"} 
[2021-03-10 08:29:31] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/inc/html.class.php line 7495
css/styles.scss is new, loading  {"user":"2051@sai-glpi-prd-01"} 
[2021-03-10 08:29:34] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/inc/html.class.php line 7495
css/dashboard.scss is new, loading  {"user":"2051@sai-glpi-prd-01"} 
[2021-03-10 08:32:38] glpiphplog.ERROR: CommonITILObject::getTemplateFieldName() in /var/www/html/glpi/inc/commonitilobject.class.php line 7950
Missing type for Ticket template!  {"user":"2256@sai-glpi-prd-01"} 
[2021-03-10 08:40:09] glpiphplog.ERROR: CommonITILObject::getTemplateFieldName() in /var/www/html/glpi/inc/commonitilobject.class.php line 7950
Missing type for Ticket template!  {"user":"2203@sai-glpi-prd-01"} 
[2021-03-10 08:42:02] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "glpiactive_entity" in /var/www/html/glpi/marketplace/formcreator/inc/issue.class.php at line 400
  Backtrace :
  inc/commondbtm.class.php:3644                      PluginFormcreatorIssue->rawSearchOptions()
  inc/commondbtm.class.php:3951                      CommonDBTM->searchOptions()
  inc/commondbtm.class.php:4023                      CommonDBTM->getSearchOptionByField()
  inc/commondbtm.class.php:1121                      CommonDBTM->filterValues()
  marketplace/formcreator/hook.php:350               CommonDBTM->add()
  inc/plugin.class.php:1350                          plugin_formcreator_hook_add_ticket()
  inc/commondbtm.class.php:1185                      Plugin::doHook()
  inc/mailcollector.class.php:824                    CommonDBTM->add()
  inc/mailcollector.class.php:1746                   MailCollector->collect()
  inc/crontask.class.php:845                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  
[2021-03-10 08:45:02] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "glpiactive_entity" in /var/www/html/glpi/marketplace/formcreator/inc/issue.class.php at line 400
  Backtrace :
  inc/commondbtm.class.php:3644                      PluginFormcreatorIssue->rawSearchOptions()
  inc/commondbtm.class.php:3951                      CommonDBTM->searchOptions()
  inc/commondbtm.class.php:4023                      CommonDBTM->getSearchOptionByField()
  inc/commondbtm.class.php:1121                      CommonDBTM->filterValues()
  marketplace/formcreator/hook.php:350               CommonDBTM->add()
  inc/plugin.class.php:1350                          plugin_formcreator_hook_add_ticket()
  inc/commondbtm.class.php:1185                      Plugin::doHook()
  inc/mailcollector.class.php:824                    CommonDBTM->add()
  inc/mailcollector.class.php:1746                   MailCollector->collect()
  inc/crontask.class.php:845                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  
[2021-03-10 08:49:52] glpiphplog.ERROR: CommonITILObject::getTemplateFieldName() in /var/www/html/glpi/inc/commonitilobject.class.php line 7950
Missing type for Ticket template!  {"user":"2203@sai-glpi-prd-01"} 
[2021-03-10 08:57:02] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "glpiactive_entity" in /var/www/html/glpi/marketplace/formcreator/inc/issue.class.php at line 400
  Backtrace :
  inc/commondbtm.class.php:3644                      PluginFormcreatorIssue->rawSearchOptions()
  inc/commondbtm.class.php:3951                      CommonDBTM->searchOptions()
  inc/commondbtm.class.php:4023                      CommonDBTM->getSearchOptionByField()
  inc/commondbtm.class.php:1121                      CommonDBTM->filterValues()
  marketplace/formcreator/hook.php:350               CommonDBTM->add()
  inc/plugin.class.php:1350                          plugin_formcreator_hook_add_ticket()
  inc/commondbtm.class.php:1185                      Plugin::doHook()
  inc/mailcollector.class.php:824                    CommonDBTM->add()
  inc/mailcollector.class.php:1746                   MailCollector->collect()
  inc/crontask.class.php:845                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  
[2021-03-10 09:02:02] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "glpiactive_entity" in /var/www/html/glpi/marketplace/formcreator/inc/issue.class.php at line 400
  Backtrace :
  inc/commondbtm.class.php:3644                      PluginFormcreatorIssue->rawSearchOptions()
  inc/commondbtm.class.php:3951                      CommonDBTM->searchOptions()
  inc/commondbtm.class.php:4023                      CommonDBTM->getSearchOptionByField()
  inc/commondbtm.class.php:1121                      CommonDBTM->filterValues()
  marketplace/formcreator/hook.php:350               CommonDBTM->add()
  inc/plugin.class.php:1350                          plugin_formcreator_hook_add_ticket()
  inc/commondbtm.class.php:1185                      Plugin::doHook()
  inc/mailcollector.class.php:824                    CommonDBTM->add()
  inc/mailcollector.class.php:1746                   MailCollector->collect()
  inc/crontask.class.php:845                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  
[2021-03-10 09:03:02] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "glpiactive_entity" in /var/www/html/glpi/marketplace/formcreator/inc/issue.class.php at line 400
  Backtrace :
  inc/commondbtm.class.php:3644                      PluginFormcreatorIssue->rawSearchOptions()
  inc/commondbtm.class.php:3951                      CommonDBTM->searchOptions()
  inc/commondbtm.class.php:4023                      CommonDBTM->getSearchOptionByField()
  inc/commondbtm.class.php:1121                      CommonDBTM->filterValues()
  marketplace/formcreator/hook.php:350               CommonDBTM->add()
  inc/plugin.class.php:1350                          plugin_formcreator_hook_add_ticket()
  inc/commondbtm.class.php:1185                      Plugin::doHook()
  inc/mailcollector.class.php:824                    CommonDBTM->add()
  inc/mailcollector.class.php:1746                   MailCollector->collect()
  inc/crontask.class.php:845                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  
[2021-03-10 09:05:02] glpiphplog.ERROR: CommonITILObject::getTemplateFieldName() in /var/www/html/glpi/inc/commonitilobject.class.php line 7950
Missing type for Ticket template!  {"user":"3929@sai-glpi-prd-01"} 
[2021-03-10 09:10:42] glpiphplog.ERROR: CommonITILObject::getTemplateFieldName() in /var/www/html/glpi/inc/commonitilobject.class.php line 7950
Missing type for Ticket template!  {"user":"2256@sai-glpi-prd-01"} 
[2021-03-10 09:17:03] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "glpiactiveprofile" in /var/www/html/glpi/inc/commonitilobject.class.php at line 2708
  Backtrace :
  inc/itilfollowup.class.php:266                     CommonITILObject::isAllowedStatus()
  inc/commondbtm.class.php:1151                      ITILFollowup->post_addItem()
  inc/mailcollector.class.php:877                    CommonDBTM->add()
  inc/mailcollector.class.php:1746                   MailCollector->collect()
  inc/crontask.class.php:845                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  
[2021-03-10 09:17:03] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /var/www/html/glpi/inc/commonitilobject.class.php at line 2708
  Backtrace :
  inc/itilfollowup.class.php:266                     CommonITILObject::isAllowedStatus()
  inc/commondbtm.class.php:1151                      ITILFollowup->post_addItem()
  inc/mailcollector.class.php:877                    CommonDBTM->add()
  inc/mailcollector.class.php:1746                   MailCollector->collect()
  inc/crontask.class.php:845                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  
[2021-03-10 09:29:42] glpiphplog.ERROR: CommonITILObject::getTemplateFieldName() in /var/www/html/glpi/inc/commonitilobject.class.php line 7950
Missing type for Ticket template!  {"user":"2045@sai-glpi-prd-01"} 
[2021-03-10 09:30:53] glpiphplog.WARNING: Test logger  
[2021-03-10 09:31:02] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "glpiactive_entity" in /var/www/html/glpi/marketplace/formcreator/inc/issue.class.php at line 400
  Backtrace :
  inc/commondbtm.class.php:3644                      PluginFormcreatorIssue->rawSearchOptions()
  inc/commondbtm.class.php:3951                      CommonDBTM->searchOptions()
  inc/commondbtm.class.php:4023                      CommonDBTM->getSearchOptionByField()
  inc/commondbtm.class.php:1121                      CommonDBTM->filterValues()
  marketplace/formcreator/hook.php:350               CommonDBTM->add()
  inc/plugin.class.php:1350                          plugin_formcreator_hook_add_ticket()
  inc/commondbtm.class.php:1185                      Plugin::doHook()
  inc/mailcollector.class.php:824                    CommonDBTM->add()
  inc/mailcollector.class.php:1746                   MailCollector->collect()
  inc/crontask.class.php:845                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  
[2021-03-10 09:33:02] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "glpiactive_entity" in /var/www/html/glpi/marketplace/formcreator/inc/issue.class.php at line 400
  Backtrace :
  inc/commondbtm.class.php:3644                      PluginFormcreatorIssue->rawSearchOptions()
  inc/commondbtm.class.php:3951                      CommonDBTM->searchOptions()
  inc/commondbtm.class.php:4023                      CommonDBTM->getSearchOptionByField()
  inc/commondbtm.class.php:1121                      CommonDBTM->filterValues()
  marketplace/formcreator/hook.php:350               CommonDBTM->add()
  inc/plugin.class.php:1350                          plugin_formcreator_hook_add_ticket()
  inc/commondbtm.class.php:1185                      Plugin::doHook()
  inc/mailcollector.class.php:824                    CommonDBTM->add()
  inc/mailcollector.class.php:1746                   MailCollector->collect()
  inc/crontask.class.php:845                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  
[2021-03-10 09:41:14] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/inc/html.class.php line 7495
css/styles.scss is new, loading  {"user":"2051@sai-glpi-prd-01"} 
[2021-0`

**Comment by cedric-anne** [comment]
These errors does not seems to be related to current issue.

Do you use some plugins ? For instance `itilcategorygroups` has been fixed recently for this issue: https://github.com/pluginsGLPI/itilcategorygroups/releases/tag/2.4.1

**Comment by OscarBeiro** [comment]
Hi Cedric,
Related to @xacobofg comment, security is important, but if the dropdowns don't show any information, in subentities, we definitely have a bigger problem.
This IDOR token is new and we still don't understand how it works, but definitely, it is causing some side problems, like :
https://github.com/glpi-project/glpi/pull/8678
https://github.com/glpi-project/glpi/pull/8438

Logs don't show any related information.

We think this is related, but if you want me to open another issue, please say it.

Thanks.

**Comment by cedric-anne** [comment]
> Hi Cedric,
> Related to @xacobofg comment, security is important, but if the dropdowns don't show any information, in subentities, we definitely have a bigger problem.
> This IDOR token is new and we still don't understand how it works, but definitely, it is causing some side problems, like :
> #8678
> #8438
> 
> Logs don't show any related information.
> 
> We think this is related, but if you want me to open another issue, please say it.
> 
> Thanks.

Hi,

Indeed, introduction of IDOR token caused many unexpected side effects. If you had a problem on another dropdown, please open an issue with a detailed way to reproduce.

Regards

**Comment by Riesuu** [comment]
I just deactivated the escalation plugin and it worked. When installing the update, I get an error.

```
SQL Error "1146": Table 'glpidb.glpi_plugin_useditemsexport_configs' doesn't exist in query "SELECT * FROM `glpi_plugin_useditemsexport_configs` WHERE `glpi_plugin_useditemsexport_configs`.`id` = '1' LIMIT 1"
PHP Warning (2): Undefined array key "is_active" in /var/www/html/glpi/marketplace/useditemsexport/setup.php at line 65
```

**Comment by cedric-anne** [comment]
OK,

Maybe you should update the plugin: https://github.com/pluginsGLPI/escalade/releases/tag/2.6.1

I close this issue as it is related to a plugin. If problem persist, please open an issue on escalade plugin repository.

Regards
